"$schema" = 'https://starship.rs/config-schema.json'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '

[package]
disabled = true

[buf]
disabled = true

[aws]
disabled = true

[python]
detect_extensions = []

